spring:
  datasource:
      url: jdbc:h2:file:./db/qihang-ecerp
      driver-class-name: org.h2.Driver
      username: qihang
      password: Andy_123
  h2:
    console:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: tech.qihangec.api.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志
#mybatis:
#  mapper-locations: classpath*:mappers/user/*.xml

server:
  port: 8080


