mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.qihang.oms.api.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志
#mybatis:
#  mapper-locations: classpath*:mappers/user/*.xml

spring:
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        usename: nacos
        passowrd: nacos
#    gateway:
#      discovery:
#        locator:
#          enabled: true # gateway 可以从 nacos 发现微服务
  config:
    import:
      - nacos:qihangec-erp.yaml?refresh=true
  application:
    name: api
server:
  port: 8080
# dubbo的配置
dubbo:
  application:
    name: api_8080
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
  config-center:
    address: nacos://127.0.0.1:8848
  metadata-report:
    address: nacos://127.0.0.1:8848



